name: tests

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    working-directory: node/express-prisma-typescript

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: node/express-prisma-typescript/yarn.lock

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma client
        run: yarn db:generate

      - name: Run tests
        run: yarn test
